---
name: nextcloud

volumes:
  postgres-data:
  nextcloud-data:

services:
  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7.2.4
    restart: unless-stopped

  office:
    image: collabora/code:24.04.1.4.1
    restart: unless-stopped
    environment:
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
      username: admin
      password: ${COLLABORA_PASS}

  nextcloud:
    image: nextcloud:29.0.0-fpm
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html:z
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${HOSTNAME}
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html:z,ro
      - ./ssl:/etc/nginx/certs:z,ro
    ports:
      - 80:80/tcp
      - 443:443/tcp
...
