---
name: nextcloud

volumes:
  postgres-data:
  nextcloud-data:

services:
  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:7.2.4
    restart: unless-stopped

  office:
    image: collabora/code:24.04.1.4.1
    restart: unless-stopped
    environment:
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
      username: admin
      password: ${COLLABORA_PASS}

  nextcloud:
    image: localhost.localdomain/local/nextcloud
    build: ./nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html:z
    env_file:
      - path: ./db.env
        required: true
      - path: ./smtp.env
        required: false
      - path: ./apps.env
        required: false
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${VHOST}
      REDIS_HOST: redis
      OVERWRITEHOST: ${VHOST}
      OVERWRITEPROTOCOL: https
      OVERWRITEWEBROOT: /
      OVERWRITECLIURL: https://${VHOST}/
      TRUSTED_PROXIES: nginx
    depends_on:
      - db
      - redis

  cron:
    image: localhost.localdomain/local/nextcloud
    build: ./nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - nextcloud

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/nginx/certs:z,ro
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      NGINX_HOST: ${VHOST}
...
